apiVersion: v1
kind: Namespace
metadata:
  name: backend-estabelecimento
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::975049952960:role/LabRole
  name: backend-cliente-serviceaccount
  namespace: backend-estabelecimento
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-cliente-hpa
  namespace: backend-estabelecimento
  labels:
    app.kubernetes.io/name: backend-cliente-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-cliente-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cliente-app
  namespace: backend-estabelecimento
  labels:
    app.kubernetes.io/name: backend-cliente-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-cliente-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-cliente-app
    spec:
      serviceAccountName: backend-cliente-serviceaccount
      containers:
        - name: backend-cliente-app
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "256m"
              memory: "512M"
            limits:
              cpu: "512m"
              memory: "2048M"
          env:
            - name: DYNAMODB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: db_url
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: aws_access_key
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: aws_secret_key
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cliente-svc
  namespace: backend-estabelecimento
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-cliente-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cliente-configmap
  namespace: backend-estabelecimento
data:
  db_url: http://localhost:4566
  aws_access_key: test
  aws_secret_key: test