aws:
  region: ${AWS_REGION:us-east-1}

amazon:
  dynamodb:
    endpoint: ${DYNAMODB_URL:http://host.docker.internal:4566}
  aws:
    accesskey: ${AWS_ACCESS_KEY:test}
    secretkey: ${AWS_SECRET_KEY:test}
    session: ${AWS_SESSION_TOKEN:test}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    servlet:
      context-path: /actuator