apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cliente-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://estabelecimento.cpmueqg0y0dn.us-east-1.rds.amazonaws.com:5432/cliente
  db_username: "postgres"
  db_password: "12345678"