apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cliente-configmap
  namespace: backend-estabelecimento
data:
  db_url: dynamodb.us-east-1.amazonaws.com
  aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
  aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  aws_session_token: "{{AWS_SESSION_TOKEN}}"